In [7]:

from torch import nn, optim
import torch
import torch.nn.functional as F
from torch.utils.data import Dataset
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np



In [1]:
from sklearn.svm import SVC
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
import pandas as pd
from sklearn.model_selection import train_test_split
df = pd.read_csv('audit_risk.csv')
trial = pd.read_csv('trial.csv')
for col in df.columns:
    if df[col].isna().any():
        print(df[df[col].isna()])
        print(df[df[col].isna()].index)
        print(col)
        df = df.loc[~df[col].isna(), :]
for col in df.columns:
    try:
       
    
        df = df.loc[~(df[col] == 'LOHARU'), :]
        df = df.loc[~(df[col] == str), :]
    except:
        continue


# iter_impute = IterativeImputer(max_iter=10, random_state=42)
# df = iter_impute.fit_transform(df)

print(df)

X = df.iloc[:, 2:-2]
X = X.apply(pd.to_numeric, errors='coerce')
y = df.iloc[:, -1]
y = y.apply(pd.to_numeric, errors='coerce')
print(X, y)


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)





Money_Value
     Sector_score LOCATION_ID  PARA_A  Score_A  Risk_A  PARA_B  Score_B  \
642         55.57           4    0.23      0.2   0.046     0.0      0.2   

     Risk_B  TOTAL  numbers  ...  RiSk_E  History  Prob  Risk_F  Score  \
642     0.0   0.23      5.0  ...     0.4        0   0.2     0.0    2.0   

     Inherent_Risk  CONTROL_RISK  Detection_Risk  Audit_Risk  Risk  
642          1.446           0.4             0.5      0.2892     0  

[1 rows x 27 columns]
Index([642], dtype='int64')
Money_Value
     Sector_score LOCATION_ID  PARA_A  Score_A  Risk_A  PARA_B  Score_B  \
0            3.89          23    4.18      0.6   2.508    2.50      0.2   
1            3.89           6    0.00      0.2   0.000    4.83      0.2   
2            3.89           6    0.51      0.2   0.102    0.23      0.2   
3            3.89           6    0.00      0.2   0.000   10.80      0.6   
4            3.89           6    0.00      0.2   0.000    0.08      0.2   
..            ...         ...     ...

In [2]:
for i in range(1, 10):
    pre = i*0.1
    class_SVC = SVC(kernel='linear', C=pre, random_state=42)
    class_SVC.fit(X_train, y_train)

    print(class_SVC.score(X_test, y_test))

0.9935483870967742
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


In [11]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.metrics import average_precision_score, precision_recall_curve
from sklearn.naive_bayes import GaussianNB
from sklearn.inspection import permutation_importance
gauss_model = GaussianNB()
gauss_model.fit(X_train, y_train)
imps = permutation_importance(gauss_model, X_test, y_test, n_repeats=10, random_state=42)
print(imps.importances_mean)
print(X_test.columns[imps.importances_mean.argsort()[::-1]])
y_pred = gauss_model.score(X_test, y_test)
print("Gaussian Naive Bayes Accuracy:", y_pred)
print("Classification Report:\n", classification_report(y_test, gauss_model.predict(X_test)))
print("Confusion Matrix:\n", confusion_matrix(y_test, gauss_model.predict(X_test)))
print("Accuracy:", accuracy_score(y_test, gauss_model.predict(X_test)))
print("Precision:", precision_score(y_test, gauss_model.predict(X_test), average='weighted'))
print("Recall:", recall_score(y_test, gauss_model.predict(X_test), average='weighted'))
print("F1 Score:", f1_score(y_test, gauss_model.predict(X_test), average='weighted'))
print("ROC AUC Score:", roc_auc_score(y_test, gauss_model.predict(X_test)))
print("Average Precision Score:", average_precision_score(y_test, gauss_model.predict(X_test)))


[ 0.02774194  0.00258065  0.03290323  0.08774194 -0.00580645  0.0883871
  0.09032258  0.04064516  0.04064516  0.04064516  0.10322581  0.11032258
  0.11354839  0.00258065  0.00516129  0.01096774  0.01677419  0.01677419
  0.01677419 -0.00129032  0.13870968  0.0116129   0.        ]
Index(['Inherent_Risk', 'Risk_D', 'Score_MV', 'Money_Value', 'TOTAL', 'Risk_B',
       'PARA_B', 'numbers', 'Score_B.1', 'Risk_C', 'Risk_A', 'PARA_A',
       'History', 'Prob', 'Risk_F', 'CONTROL_RISK', 'RiSk_E', 'PROB',
       'District_Loss', 'Score_A', 'Detection_Risk', 'Score', 'Score_B'],
      dtype='object')
Gaussian Naive Bayes Accuracy: 0.9612903225806452
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.94      0.97        95
           1       0.91      1.00      0.95        60

    accuracy                           0.96       155
   macro avg       0.95      0.97      0.96       155
weighted avg       0.96      0.96      0.96       155

Co

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.score(X_test, y_test)
print("Random Forest Accuracy:", y_pred_rf)
print("Classification Report:\n", classification_report(y_test, rf_model.predict(X_test)))
print("Confusion Matrix:\n", confusion_matrix(y_test, rf_model.predict(X_test)))
print("Accuracy:", accuracy_score(y_test, rf_model.predict(X_test)))
print("Precision:", precision_score(y_test, rf_model.predict(X_test), average='weighted'))
print("Recall:", recall_score(y_test, rf_model.predict(X_test), average='weighted'))
print("F1 Score:", f1_score(y_test, rf_model.predict(X_test), average='weighted'))
print("ROC AUC Score:", roc_auc_score(y_test, rf_model.predict(X_test)))
print("Average Precision Score:", average_precision_score(y_test, rf_model.predict(X_test)))

Random Forest Accuracy: 1.0
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        95
           1       1.00      1.00      1.00        60

    accuracy                           1.00       155
   macro avg       1.00      1.00      1.00       155
weighted avg       1.00      1.00      1.00       155

Confusion Matrix:
 [[95  0]
 [ 0 60]]
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0
ROC AUC Score: 1.0
Average Precision Score: 1.0


In [6]:
from sklearn.neural_network import MLPClassifier
mlp_model = MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=500, random_state=42)
mlp_model.fit(X_train, y_train)
y_pred_mlp = mlp_model.score(X_test, y_test)
print("MLP Classifier Accuracy:", y_pred_mlp)
print("Classification Report:\n", classification_report(y_test, mlp_model.predict(X_test)))
print("Confusion Matrix:\n", confusion_matrix(y_test, mlp_model.predict(X_test)))
print("Accuracy:", accuracy_score(y_test, mlp_model.predict(X_test)))
print("Precision:", precision_score(y_test, mlp_model.predict(X_test), average='weighted'))
print("Recall:", recall_score(y_test, mlp_model.predict(X_test), average='weighted'))
print("F1 Score:", f1_score(y_test, mlp_model.predict(X_test), average='weighted'))



MLP Classifier Accuracy: 1.0
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        95
           1       1.00      1.00      1.00        60

    accuracy                           1.00       155
   macro avg       1.00      1.00      1.00       155
weighted avg       1.00      1.00      1.00       155

Confusion Matrix:
 [[95  0]
 [ 0 60]]
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0


In [12]:
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)
y_pred_knn = knn_model.score(X_test, y_test)
print("KNN Classifier Accuracy:", y_pred_knn)
print("Classification Report:\n", classification_report(y_test, knn_model.predict(X_test)))
print("Confusion Matrix:\n", confusion_matrix(y_test, knn_model.predict(X_test)))
print("Accuracy:", accuracy_score(y_test, knn_model.predict(X_test)))
print("Precision:", precision_score(y_test, knn_model.predict(X_test), average='weighted'))
print("Recall:", recall_score(y_test, knn_model.predict(X_test), average='weighted'))
print("F1 Score:", f1_score(y_test, knn_model.predict(X_test), average='weighted'))

KNN Classifier Accuracy: 0.9870967741935484
Classification Report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99        95
           1       1.00      0.97      0.98        60

    accuracy                           0.99       155
   macro avg       0.99      0.98      0.99       155
weighted avg       0.99      0.99      0.99       155

Confusion Matrix:
 [[95  0]
 [ 2 58]]
Accuracy: 0.9870967741935484
Precision: 0.987362820086465
Recall: 0.9870967741935484
F1 Score: 0.9870546291233825
